apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: my-application-docker
spec:

  output:
    to:
      kind: ImageStreamTag
      name: 'my-application-docker:latest'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/mmumshad/simple-webapp-docker.git'
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          172.30.1.1:5000/openshift/python@sha256:ce717a1f4817162287e2357d4c2db602b80487b3cc7df8db24ae709e9d322af2
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: be3176bd722bf11d
      type: Generic
    - github:
        secret: bcdd9e63bf255b80
      type: GitHub
